FreddosExpenses/Controllers/ExpenseApprovalProcessingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FreddosExpenses.Data;
using FreddosExpenses.ViewModels;
using FreddosExpenses.Models;

namespace FreddosExpenses.Controllers
{
    public class ExpenseApprovalProcessingController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ExpenseApprovalProcessingController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: ExpenseApprovalProcessing
        public async Task<IActionResult> Index()
        {
            var result = await _context.Expense
                .Where(item => item.ExpenseApprovals.OrderByDescending(p => p.Id).Select(status => status.IsSubmitted == false && status.IsApproved == true && status.IsProcessed == false).FirstOrDefault())
                .ToListAsync();
            var model = new ExpenseApprovalProcessingSelectionViewModal();


            foreach (var expense in result)
            {
                var editorViewModel = new ExpenseApprovalProcessingViewModal()
                {
                    Amount = expense.Amount,
                    ExpenseDate = expense.ExpenseDate,
                    Selected = false,
                    SubmittedDate = expense.SubmittedDate,
                    Description = expense.Description,
                    Id = expense.Id,
                    CreatedByUserName = expense.CreatedByUserName
                };

                model.ExpenseApproval.Add(editorViewModel);
            }

            return View(model);
        }

        // GET: ExpenseApprovalProcessing/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var Expense = await _context.Expense
                .Include(r => r.ExpenseReceipts)
                .SingleOrDefaultAsync(m => m.Id == id);

            var editorViewModel = new ExpenseApprovalProcessingViewModal();

            if (Expense == null)
            {
                return NotFound();
            }

            editorViewModel = new ExpenseApprovalProcessingViewModal()
            {
                Amount = Expense.Amount,
                ExpenseDate = Expense.ExpenseDate,
                Selected = false,
                SubmittedDate = Expense.SubmittedDate,
                Description = Expense.Description,
                Id = Expense.Id,
                ExpenseReceipts = Expense.ExpenseReceipts,
                CreatedByUserName = Expense.CreatedByUserName
            };

            return View(editorViewModel);
        }

        // GET: ExpenseApprovalProcessing/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: ExpenseApprovalProcessing/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ExpenseApprovalProcessingSelectionViewModal ExpensesForApprovalList)
        {
            if (ModelState.IsValid)
            {
                var result = ExpensesForApprovalList.ExpenseApproval.OfType<ExpenseApprovalProcessingViewModal>().Where(s => s.Selected == true);

                foreach (var expenseApproval in result)
                {
                    var existingExpense = await _context.Expense
                        .Include(r => r.ExpenseReceipts)
                        .Include(r => r.ExpenseApprovals)
                        .SingleOrDefaultAsync(m => m.Id == expenseApproval.Id);

                    if (existingExpense != null)
                    {
                        existingExpense.ExpenseApprovals.Add(new ExpenseApproval()
                        {
                            ExpenseId = existingExpense.Id,
                            Comment = string.Empty,
                            IsProcessed = true
                        });

                        _context.Entry(existingExpense).CurrentValues.SetValues(existingExpense);
                        _context.Update(existingExpense);
                        await _context.SaveChangesAsync();
                    }
                }
            }
            return RedirectToAction("Index");
        }

        // GET: ExpenseApprovalProcessing/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var Expense = await _context.Expense.SingleOrDefaultAsync(m => m.Id == id);
            if (Expense == null)
            {
                return NotFound();
            }
            return View(Expense);
        }

        // POST: ExpenseApprovalProcessing/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Selected,Id,SubmittedDate,ExpenseDate,Amount,Description")] Expense Expense)
        {
            if (id != Expense.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(Expense);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ExpenseExists(Expense.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(Expense);
        }

        // GET: ExpenseApprovalProcessing/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var Expense = await _context.Expense
                .SingleOrDefaultAsync(m => m.Id == id);
            if (Expense == null)
            {
                return NotFound();
            }

            return View(Expense);
        }

        // POST: ExpenseApprovalProcessing/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var Expense = await _context.Expense.SingleOrDefaultAsync(m => m.Id == id);
            _context.Expense.Remove(Expense);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ExpenseExists(int id)
        {
            return _context.Expense.Any(e => e.Id == id);
        }
    }
}

FreddosExpenses/Views/ExpenseApprovalProcessing/Create.cshtml
@model FreddosExpenses.ViewModels.ExpenseApprovalProcessingViewModal

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>ExpenseApprovalProcessingViewModal</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <div class="checkbox">
                    <label>
                        <input asp-for="Selected" /> @Html.DisplayNameFor(model => model.Selected)
                    </label>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="SubmittedDate" class="control-label"></label>
                <input asp-for="SubmittedDate" class="form-control" />
                <span asp-validation-for="SubmittedDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ExpenseDate" class="control-label"></label>
                <input asp-for="ExpenseDate" class="form-control" />
                <span asp-validation-for="ExpenseDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Amount" class="control-label"></label>
                <input asp-for="Amount" class="form-control" />
                <span asp-validation-for="Amount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

FreddosExpenses/Views/ExpenseApprovalProcessing/Delete.cshtml
@model FreddosExpenses.ViewModels.ExpenseApprovalProcessingViewModal

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ExpenseApprovalProcessingViewModal</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Selected)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Selected)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.SubmittedDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SubmittedDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ExpenseDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ExpenseDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Amount)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Amount)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

FreddosExpenses/Views/ExpenseApprovalProcessing/Details.cshtml
@model FreddosExpenses.ViewModels.ExpenseApprovalProcessingViewModal

@{
    ViewData["Title"] = "Details";
}

<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <div class="well mt-20">
            <h4>Expense Details</h4>
            <hr />
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.SubmittedDate)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.SubmittedDate)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.ExpenseDate)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.ExpenseDate)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.Amount)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.Amount)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.Description)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.Description)
                </dd>
				<dt>
                    @Html.DisplayNameFor(model => model.CreatedByUserName)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.CreatedByUserName)
                </dd>
                @if (Model.ExpenseReceipts.Count == 0)
                {
                    <dd>
                        <img class="receipt-img" asp-for="receipt" src="@string.Format("https://{0}/receipts/no-receipt-no-return.jpg", Context.Request.Host)" />
                    </dd>
                }
                else
                {
                    foreach (var receipt in Model.ExpenseReceipts)
                    {
                        <dd>
                            <img class="receipt-img" asp-for="receipt" src="@string.Format("https://{0}/receipts/{1}", Context.Request.Host, receipt.StoredFileName)" />
                        </dd>
                    }
                }
            </dl>
        </div>
        <div>
            <a asp-action="Index">Back to List</a>
        </div>
    </div>
</div>

FreddosExpenses/Views/ExpenseApprovalProcessing/Edit.cshtml
@model FreddosExpenses.ViewModels.ExpenseApprovalProcessingViewModal

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>ExpenseApprovalProcessingViewModal</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <div class="checkbox">
                    <label>
                        <input asp-for="Selected" /> @Html.DisplayNameFor(model => model.Selected)
                    </label>
                </div>
            </div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="SubmittedDate" class="control-label"></label>
                <input asp-for="SubmittedDate" class="form-control" />
                <span asp-validation-for="SubmittedDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ExpenseDate" class="control-label"></label>
                <input asp-for="ExpenseDate" class="form-control" />
                <span asp-validation-for="ExpenseDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Amount" class="control-label"></label>
                <input asp-for="Amount" class="form-control" />
                <span asp-validation-for="Amount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

FreddosExpenses/Views/ExpenseApprovalProcessing/Index.cshtml
@model FreddosExpenses.ViewModels.ExpenseApprovalProcessingSelectionViewModal

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<div class="well mt-20">
    <h4 class="mt-10 mb-20">Expenses Ready for Processing</h4>
    <form asp-action="Create" asp-controller="ExpenseApprovalProcessing" enctype="multipart/form-data">
        <table class="table">
            <thead>
                <tr>
                    <th>
                        Process
                    </th>
                    <th>
                        Expense Date
                    </th>
                    <th>
                        Amount
                    </th>
                    <th>
                        Description
                    </th>
					<th>
                        Created By
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @Html.EditorFor(model => model.ExpenseApproval)
            </tbody>
        </table>
        <div class="form-group">
            <input type="submit" value="Submit Processed" class="btn btn-primary mr-10" />
        </div>
    </form>
</div>