FreddosExpenses/Controllers/ExpensesController.cs
using FreddosExpenses.Data;
using FreddosExpenses.Models;
using FreddosExpenses.Models.Constants;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Options;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Http.Headers;
using System.Threading.Tasks;

namespace FreddosExpenses.Controllers
{
    [Authorize(Roles = ConstantsRoleNames.Employee + "," + ConstantsRoleNames.Manager)]
	public class ExpensesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IOptions<ApplicationConfiguration> _optionsApplicationConfiguration;
        private readonly IHostingEnvironment _hostingEnvironment;
        private readonly string _expenseReceiptPath;
        private readonly UserManager<ApplicationUser> _userManager;
        private  string _userId;
        private  string _userName;

        public ExpensesController(
            ApplicationDbContext context, 
            IOptions<ApplicationConfiguration> o, 
            IHostingEnvironment h,
            UserManager<ApplicationUser> userManager)
        {
            _userManager = userManager;
            _context = context;
            _optionsApplicationConfiguration = o;
            _hostingEnvironment = h;
            _expenseReceiptPath = string.Format("{0}/{1}/", h.WebRootPath, "receipts");
            //_userId = _userManager.GetUserId(User);
            //_userName = _userManager.GetUserName(User);
        }

        // GET: Expenses
        public async Task<IActionResult> Index()
        {
            _userId = _userManager.GetUserId(User);
            return View(await _context.Expense
                .Include(r => r.ExpenseApprovals)
                .Where(item => item.CreatedByUserId == _userId && (item.ExpenseApprovals.Count == 0 || item.ExpenseApprovals.OrderByDescending(p => p.Id).Select(status => status.IsSubmitted == false && status.IsApproved == false && status.IsProcessed == false).FirstOrDefault()))
                .ToListAsync());
        }

        // GET: Expenses/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var expense = await _context.Expense
                .Include(r => r.ExpenseReceipts)
                .Include(r => r.ExpenseApprovals)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (expense == null)
            {
                return NotFound();
            }

            return View(expense);
        }

        // GET: Expenses/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Expenses/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Expense expense)
        {
            if (ModelState.IsValid)
            {
                expense.SubmittedDate = DateTime.Now;
                expense.ExpenseReceipts = new List<ExpenseReceipt>();
                expense.ExpenseApprovals = new List<ExpenseApproval>();

                _userId = _userManager.GetUserId(User);
                _userName = _userManager.GetUserName(User);

                expense.CreatedByUserName = _userName;
                expense.CreatedByUserId = _userId;

                

                expense.ExpenseApprovals.Add(new ExpenseApproval()
                {
                    ExpenseId = expense.Id,
                    Comment = string.Empty,
                    IsSubmitted = false
                });

                if (expense.Images != null && expense.Images.Count > 0)
                {
                    foreach (var file in expense.Images)
                    {
                        if (file.Length > 0)
                        {
                            var fileName = ContentDispositionHeaderValue.Parse(file.ContentDisposition).FileName.Trim('"');
                            var storedfilename = string.Format("{0}_{1}", Guid.NewGuid().ToString("N"), fileName);
                            // Extension method update RC2 has removed this 
                            await file.SaveAsAsync(Path.Combine(_expenseReceiptPath, storedfilename));

                            if (expense.ExpenseReceipts.Count > 0)
                            {
                                expense.ExpenseReceipts.ToList()[0].ContentType = file.ContentType;
                                expense.ExpenseReceipts.ToList()[0].StoredFileName = storedfilename;
                                expense.ExpenseReceipts.ToList()[0].UserUploadedFileName = fileName;
                            }
                            else
                            {
                                expense.ExpenseReceipts.Add(new ExpenseReceipt()
                                {
                                    ContentType = file.ContentType,
                                    StoredFileName = storedfilename,
                                    UserUploadedFileName = fileName
                                });
                            }
                        }
                    }
                }

                _context.Add(expense);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(expense);
        }

        // GET: Expenses/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var expense = await _context.Expense
                .Include(r => r.ExpenseReceipts)
                .Include(r => r.ExpenseApprovals)
                .SingleOrDefaultAsync(m => m.Id == id);

            if (expense == null)
            {
                return NotFound();
            }
            return View(expense);
        }

        // POST: Expenses/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Expense expense)
        {
            if (id != expense.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var existingExpense = _context.Expense
                            .Include(r => r.ExpenseReceipts)
                            .Include(r => r.ExpenseApprovals)
                            .SingleOrDefault(m => m.Id == id);

                    if (existingExpense != null)
                    {
                        _context.Entry(existingExpense).CurrentValues.SetValues(expense);
                    }

                    existingExpense.SubmittedDate = DateTime.Now;

                    _userId = _userManager.GetUserId(User);
                    _userName = _userManager.GetUserName(User);

                    existingExpense.CreatedByUserName = _userName;
                    existingExpense.CreatedByUserId = _userId;

                    existingExpense.ExpenseApprovals.Add(new ExpenseApproval()
                    {
                        ExpenseId = existingExpense.Id,
                        Comment = string.Empty,
                        IsSubmitted = false
                    });

                    if (expense.Images != null && expense.Images.Count > 0)
                    {
                        if (existingExpense.ExpenseReceipts == null)
                        {
                            existingExpense.ExpenseReceipts = new List<ExpenseReceipt>();
                        }

                        foreach (var file in expense.Images)
                        {
                            if (file.Length > 0)
                            {
                                var fileName = ContentDispositionHeaderValue.Parse(file.ContentDisposition).FileName.Trim('"');
                                var storedfilename = string.Format("{0}_{1}", Guid.NewGuid().ToString("N"), fileName);
                                // Extension method update RC2 has removed this 
                                await file.SaveAsAsync(Path.Combine(_expenseReceiptPath, storedfilename));

                                if (existingExpense.ExpenseReceipts.Count > 0)
                                {
                                    existingExpense.ExpenseReceipts.ToList()[0].ExpenseId = existingExpense.Id;
                                    existingExpense.ExpenseReceipts.ToList()[0].ContentType = file.ContentType;
                                    existingExpense.ExpenseReceipts.ToList()[0].StoredFileName = storedfilename;
                                    existingExpense.ExpenseReceipts.ToList()[0].UserUploadedFileName = fileName;
                                }
                                else
                                {
                                    existingExpense.ExpenseReceipts.Add(new ExpenseReceipt()
                                    {
                                        ContentType = file.ContentType,
                                        StoredFileName = storedfilename,
                                        UserUploadedFileName = fileName
                                    });
                                }
                                
                            }
                        }
                    }

FreddosExpenses/Views/Expenses/Create.cshtml
@model FreddosExpenses.Models.Expense
@{
    ViewData["Title"] = "Create";
}
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <div class="well mt-20">
            <form asp-action="Create" asp-controller="Expenses" enctype="multipart/form-data">
                <h4>Create a new expense</h4>
                <hr />
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="ExpenseDate" class="control-label"></label>
                    <input asp-for="ExpenseDate" class="form-control" type="date" />
                    <span asp-validation-for="ExpenseDate" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Amount" class="control-label"></label>
                    <input asp-for="Amount" class="form-control" />
                    <span asp-validation-for="Amount" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Description" class="control-label"></label>
                    <input asp-for="Description" class="form-control" />
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="file" name="Images" />
                </div>
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-primary mr-10" />
                    <a asp-action="Index" class="btn btn-default">Cancel</a>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FreddosExpenses/Views/Expenses/Delete.cshtml
@model FreddosExpenses.Models.Expense

@{
    ViewData["Title"] = "Delete";
}

<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <h3>Are you sure you want to delete this?</h3>
        <div class="well mt-20">
            <h4>Expense Details</h4>
            <hr />
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.SubmittedDate)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.SubmittedDate)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.ExpenseDate)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.ExpenseDate)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.Amount)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.Amount)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.Description)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.Description)
                </dd>
                <dt>
                    Scanned Receipt
                </dt>
                @if (Model.ExpenseReceipts.Count == 0)
                {
                    <dd>
                        <img class="receipt-img" asp-for="receipt" src="@string.Format("https://{0}/receipts/no-receipt-no-return.jpg", Context.Request.Host)" />
                    </dd>
                }
                else
                {
                    foreach (var receipt in Model.ExpenseReceipts)
                    {
                        <dd>
                            <img class="receipt-img" asp-for="receipt" src="@string.Format("https://{0}/receipts/{1}", Context.Request.Host, receipt.StoredFileName)" />
                        </dd>
                    }
                }
                @*<dt>
                        @Html.DisplayNameFor(model => model.Image)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.Image)
                    </dd>*@
            </dl>

            <form asp-action="Delete">
                <input type="hidden" asp-for="Id" />
                <input type="submit" value="Delete" class="btn btn-primary" /> |
                <a asp-action="Index">Back to List</a>
            </form>
        </div>
    </div>
</div>

FreddosExpenses/Views/Expenses/Details.cshtml
@model FreddosExpenses.Models.Expense

@{
    ViewData["Title"] = "Details";
}


<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <div class="well mt-20">
            <h4>Expense Details</h4>
            <hr />
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.SubmittedDate)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.SubmittedDate)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.ExpenseDate)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.ExpenseDate)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.Amount)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.Amount)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.Description)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.Description)
                </dd>
				<dt>
                    @Html.DisplayNameFor(model => model.CreatedByUserName)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.CreatedByUserName)
                </dd>
                <dt>
                    Scanned Receipt
                </dt>
                @if (Model.ExpenseReceipts.Count == 0)
                {
                    <dd>
                        <img class="receipt-img" asp-for="receipt" src="@string.Format("https://{0}/receipts/no-receipt-no-return.jpg", Context.Request.Host)" />
                    </dd>
                }
                else
                {
                    foreach (var receipt in Model.ExpenseReceipts)
                    {
                    <dd>
                        <img class="receipt-img" asp-for="receipt" src="@string.Format("https://{0}/receipts/{1}", Context.Request.Host, receipt.StoredFileName)" />
                    </dd>
                    }
                }
                @*<dt>
                        @Html.DisplayNameFor(model => model.Image)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.Image)
                    </dd>*@
            </dl>
            <div>
                <a asp-action="Edit" class="btn btn-primary" asp-route-id="@Model.Id">Edit</a> |
                <a asp-action="Index">Back to List</a>
            </div>
        </div>
    </div>
</div>

FreddosExpenses/Views/Expenses/Edit.cshtml
@model FreddosExpenses.Models.Expense

@{
    ViewData["Title"] = "Update";
}

<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <div class="well">
            <form asp-action="Edit" asp-controller="Expenses" enctype="multipart/form-data">
                <h4>Edit Expense</h4>
                <hr />
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="Id" />
                @*<div class="form-group">
                    <label asp-for="SubmittedDate" class="control-label"></label>
                    <input asp-for="SubmittedDate" class="form-control" />
                    <span asp-validation-for="SubmittedDate" class="text-danger"></span>
                </div>*@
                <div class="form-group">
                    <label asp-for="ExpenseDate" class="control-label"></label>
                    <input asp-for="ExpenseDate" class="form-control" type="date" />
                    <span asp-validation-for="ExpenseDate" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Amount" class="control-label"></label>
                    <input asp-for="Amount" class="form-control" />
                    <span asp-validation-for="Amount" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Description" class="control-label"></label>
                    <input asp-for="Description" class="form-control" />
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
@if (Model.ExpenseReceipts.Count == 0)
{
    <div class="form-group">
        <label class="control-label">Scanned Receipt</label>
        <img class="receipt-img" asp-for="receipt" src="@string.Format("https://{0}/receipts/no-receipt-no-return.jpg",Context.Request.Host)" />
    </div>
}
else
{
    foreach (var ExpenseReceipt in Model.ExpenseReceipts)
    {
                <div class="form-group">
                    <label class="control-label">Scanned Receipt</label>
                    <img class="receipt-img" asp-for="receipt" src="@string.Format("https://{0}/receipts/{1}",Context.Request.Host, ExpenseReceipt.StoredFileName)" />
                </div>
    }
}    
                <div class="form-group">
                    <label class="control-label">Upload a new receipt</label>
                    <input type="file" name="Images" />
                </div>
                <div class="form-group">
                    <input type="submit" value="Save" class="btn btn-primary" />
                    <a asp-action="Index" class="btn btn-default">Cancel</a>
                </div>
            </form>
        </div>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FreddosExpenses/Views/Expenses/Index.cshtml
@model IEnumerable<FreddosExpenses.Models.Expense>
@{
    ViewData["Title"] = "Expenses";
}

<div class="well mt-20">
    <h4 class="mt-10 mb-20">Expenses</h4>
    <a class="btn btn-primary mb-20" asp-action="Create">Create New</a>
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.SubmittedDate)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ExpenseDate)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Amount)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Description)
                </th>
                <th>
                    Comment
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CreatedByUserName)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.SubmittedDate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ExpenseDate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Amount)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Description)
                    </td>
                    <td>
                        @if (item.ExpenseApprovals != null && item.ExpenseApprovals.Count > 0)
                        {
                            @item.ExpenseApprovals.LastOrDefault().Comment
                        }
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CreatedByUserName)
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                        <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                        <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>